dist: trusty

language: java

jdk:
  - openjdk8

script:
  - mvn site post-site

deploy:
  local_dir: target/site
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master